const ADJECTIVES = [

	{
		en: 'satisfied',
		tr: '[ˈsætɪsfaɪd]',
		ru: 'удовлетворённый',
		ru_example: 'Ты был удовлетворён этим результатом?',
		en_example: 'Were you satisfied with this result?',
	},
	{
		en: 'depressed',
		tr: '[dɪˈprest]',
		ru: 'подавленный',
		ru_example: 'Тот человек чувствует себя подавленным?',
		en_example: 'Does that man feel depressed?',
	},
	{
		en: 'silly',
		tr: '[ˈsɪli]',
		ru: 'глупый',
		ru_example: 'Конечно, я смогу избавиться от этих глупых ошибок',
		en_example: "Of course, I'll be able to get rid of these silly mistakes",
	},
	{
		en: 'unexpected',
		tr: '[ˌʌnɪkˈspektɪd]',
		ru: 'неожиданный',
		ru_example: 'Эти изменения очень неожиданные для них?',
		en_example: 'Are these changes very unexpected for them?',
	},
	{
		en: 'harmful',
		tr: '[ˈhɑːmfᵊl]',
		ru: 'вредный',
		ru_example: 'Курение очень вредно для нашего здоровья',
		en_example: 'Smoking is very harmful to our health',
	},
	{
		en: 'spare',
		tr: '[speə]',
		ru: 'запасной; свободный [про время; про что-то неиспользуемое]',
		ru_example: `1)Запасное колесо находится в багажнике <br> 2)Я обожаю заниматься этим в своё свободное время`,
		en_example: `1)The spare tyre is in the boot <br> 2)I enjoy doing this in my spare time`,
	},
	{
		en: 'disappointed',
		tr: '[ˌdɪsəˈpɔɪntɪd]',
		ru: 'разочарованный',
		ru_example: 'Эти мужчины очень разочарованы',
		en_example: 'These men are very disappointed',
	},
	{ en: 'fond', tr: '[fɒnd]', ru: 'любящий, нежный', ru_example: 'Я люблю спорт', en_example: "I'm fond of sport" },
	{
		en: 'ridiculous',
		tr: '[rɪˈdɪkjələs]',
		ru: 'смешной, нелепый',
		ru_example: 'Цена была так высока, и мы все понимали, что это было абсолютно нелепо',
		en_example: 'The price was so high and we all understood that it was absolutely ridiculous',
	},
	{
		en: 'overcrowded [with]',
		tr: '[ˌəʊvəˈkraʊdɪd]',
		ru: 'переполненный [чем-то]',
		ru_example: 'Та область переполнена туристами?',
		en_example: 'Is that area overcrowded with tourists?',
	},

	{
		en: 'shocking',
		tr: '[ˈʃɒkɪŋ]',
		ru: 'шокирующий',
		ru_example: 'Что там такого шокирующего?',
		en_example: 'What is so shocking there?',
	},
	{
		en: 'accurate',
		tr: '[ˈækjərət]',
		ru: 'точный',
		ru_example: 'Чьё описание более точное?',
		en_example: 'Whose description is more accurate?',
	},
	{
		en: 'experienced',
		tr: '[ɪkˈspɪəriənst]',
		ru: 'опытный',
		ru_example: 'Он очень опытный учитель',
		en_example: "He's a very experienced teacher",
	},
	{
		en: 'reliable',
		tr: '[rɪˈlaɪəbᵊl]',
		ru: 'надёжный',
		ru_example: 'Эта машина надежная?',
		en_example: 'Is this car reliable?',
	},
	{
		en: 'ambitious',
		tr: '[æmˈbɪʃəs]',
		ru: 'амбициозный',
		ru_example: 'Студент очень амбициозный',
		en_example: 'The student is very ambitious',
	},
	{ en: 'lonely', tr: '[ˈləʊnli]', ru: 'одинокий', ru_example: 'Она была одинока?', en_example: 'Was she lonely?' },
	{
		en: 'outstanding',
		tr: '[aʊtˈstændɪŋ]',
		ru: 'выдающийся',
		ru_example: 'Это было вадающееся достижение',
		en_example: 'It was an outstanding achievement',
	},
	{
		en: 'pleasant',
		tr: '[ˈplezᵊnt]',
		ru: 'приятный',
		ru_example: 'У неё очень приятная улыбка',
		en_example: 'She has a very pleasant smile',
	},
	{
		en: 'low-quality',
		tr: '[ləʊ]-[ˈkwɒləti]',
		ru: 'низкокачественный',
		ru_example: 'Никогда больше не соглашайтесь на низкокачественный контент',
		en_example: 'Never settle again for low-quality content',
	},
	{
		en: 'proud',
		tr: '[praʊd]',
		ru: 'гордый',
		ru_example: 'Ты гордишься своими достижениями?',
		en_example: 'Are you proud of your achievements?',
	},

	{
		en: 'tremendous',
		tr: '[trɪˈmɛndəs]',
		ru: 'огромный',
		ru_example: 'Я хотел бы поблагодарить тебя за твою огромную поддержку',
		en_example: "I'd like to thank you for your tremendous support",
	},
	{
		en: 'polite',
		tr: '[pəˈlaɪt]',
		ru: 'вежливый',
		ru_example: 'Я думаю, людям следует быть более вежливыми',
		en_example: 'I think people should be more polite',
	},
	{ en: 'mean*', tr: '[miːn]', ru: 'подлый', ru_example: 'Ты подлый человек', en_example: "You're a mean person" },
	{
		en: 'inexpensive',
		tr: '[ˌɪnɪkˈspensɪv]',
		ru: 'недорогой',
		ru_example: 'Это недорогие часы?',
		en_example: 'Is it an inexpensive watch?',
	},
	{
		en: 'independent',
		tr: '[ˌɪndɪˈpendənt]',
		ru: 'независимый',
		ru_example: 'Он не чувствует себя финансово независимым',
		en_example: "He doesn't feel financially independent",
	},
	{
		en: 'profitable',
		tr: '[ˈprɒfɪtəbᵊl]',
		ru: 'прибыльный',
		ru_example: 'Его бизнес не прибыльный',
		en_example: "His business isn't profitable",
	},
	{
		en: 'incorrect',
		tr: '[ˌɪnkəˈrekt]',
		ru: 'неправильный, неточный',
		ru_example: 'Этот ответ неверный?',
		en_example: 'Is this anwer incorrect?',
	},
	{
		en: 'tiring',
		tr: '[ˈtaɪərɪŋ]',
		ru: 'утомительный',
		ru_example: 'Поездка была совсем не утомительной',
		en_example: "The trip wasn't tiring at all",
	},
	{
		en: 'terrible / awful',
		tr: '[ˈterəbl] / [ˈɔːfᵊl]',
		ru: 'ужасный',
		ru_example: 'Те люди живут в ужасных условиях',
		en_example: 'Those people live in terrible / awful conditions',
	},
	{
		en: 'divorced',
		tr: '[dɪˈvɔːst]',
		ru: 'разведённый',
		ru_example: 'Когда он разведётся?',
		en_example: 'When will he get divorced?',
	},

	{
		en: 'obvious',
		tr: '[ˈɒbviəs]',
		ru: 'очевидный',
		ru_example: 'Это очевидный ответ',
		en_example: 'This is the obvious answer',
	},
	{ en: 'generous', tr: '[ˈʤenᵊrəs]', ru: 'щедрый', ru_example: 'Ты такой щедрый', en_example: "You're so generous" },
	{
		en: 'colourful',
		tr: '[ˈkʌləfᵊl]',
		ru: 'красочный',
		ru_example: 'Это красочный пейзаж',
		en_example: "It's a colorful landscape",
	},
	{
		en: 'complete*',
		tr: '[kəmˈpliːt]',
		ru: 'полный',
		ru_example: 'Почему это будет совершенно пустая трата времени?',
		en_example: 'Why will it be a complete waste of time?',
	},
	{
		en: 'urgent',
		tr: '[ˈɜːʤᵊnt]',
		ru: 'срочный',
		ru_example: 'Они информируют его, когда что-то действительно срочное происходит',
		en_example: 'They inform him when something really urgent happens',
	},
	{
		en: 'lovely',
		tr: '[ˈlʌvli]',
		ru: 'прекрасный',
		ru_example: 'Она живёт в прекрасном месте',
		en_example: 'She lives in a lovely place',
	},
	{
		en: 'convenient',
		tr: '[kənˈviːniənt]',
		ru: 'удобный, подходящий',
		ru_example: 'То время для них удобно?',
		en_example: 'Is that time convenient for them?',
	},
	{
		en: 'nearest',
		tr: '[ˈnɪərɪst]',
		ru: 'ближайший',
		ru_example: 'Эта дорога ведёт к ближайшему отелю',
		en_example: 'This road leands to the nearest hotel',
	},
	{
		en: 'acquaintance',
		tr: '[əˈkweɪntᵊns]',
		ru: 'знакомый',
		ru_example: 'Мой знакомый не хочет становиться предпринимателем, потому что он думает, это очень рисковано',
		en_example: "My acquaintance doesn't want to become an entrepreneur because he thinks it's very risky",
	},
	{
		en: 'prestigious',
		tr: '[presˈtɪʤəs]',
		ru: 'престижный',
		ru_example: 'Я хочу окончить очень престижный университет',
		en_example: 'I want to graduate from a very prestigious university',
	},

	{
		en: 'wise',
		tr: '[waɪz]',
		ru: 'мудрый',
		ru_example: 'Это было очень мудрое решение',
		en_example: 'It was a very wise decision',
	},
	{ en: 'rude', tr: '[ruːd]', ru: 'грубый', ru_example: 'Ты такой грубый', en_example: "You're so rude" },
	{
		en: 'attractive',
		tr: '[əˈtræktɪv]',
		ru: 'привлекательный',
		ru_example: 'Это для тебя действительно было привлекательное предложение?',
		en_example: 'Was it really an attractive offer for you?',
	},
	{
		en: 'unforgettable',
		tr: '[ˌʌnfəˈɡetəbᵊl]',
		ru: 'незабываемый',
		ru_example: 'Он думает, это будет назабываемая вечеринка',
		en_example: "He thinks it'll be an unforgettable party",
	},
	{
		en: 'patient*',
		tr: '[ˈpeɪʃnt]',
		ru: 'терпеливый',
		ru_example: 'Ты слишком терпеливый',
		en_example: "You're too patient",
	},
	{
		en: 'spoilt',
		tr: '[spɔɪlt]',
		ru: 'испорченный',
		ru_example: 'Это испорченное молоко',
		en_example: "It's spoiled milk",
	},
	{
		en: 'splendid',
		tr: '[ˈsplɛndɪd]',
		ru: 'великолепный, роскошный',
		ru_example: 'Мы забронировали великолепную квартиру с видом на океан',
		en_example: 'We booked a splendid apartament with a view of the ocean',
	},
	{
		en: 'predictable',
		tr: '[prɪˈdɪktəbᵊl]',
		ru: 'предсказуемый',
		ru_example: 'Результаты совсем не были предсказуемыми',
		en_example: "The results weren't predictable at all",
	},
	{ en: 'thin', tr: '[θɪn]', ru: 'худой', ru_example: 'Ты болезненно худой', en_example: "You're painfully thin" },
	{
		en: 'innocent',
		tr: '[ˈɪnəsᵊnt]',
		ru: 'невиновный',
		ru_example: 'Полиция должна остановить их, потому что они могут убивать невинных людей',
		en_example: 'The police must stop them because they can kill innocent people',
	},

	{
		en: 'huge',
		tr: '[hjuːʤ]',
		ru: 'огромный',
		ru_example: 'Я поблагодарил его за его огромную поддержку',
		en_example: 'I thanked him for his huge support',
	},
	{ en: 'confident', tr: '[ˈkɒnfɪdᵊnt]', ru: 'уверенный', ru_example: "Твой друг чувствует себя достаточно уверенно, когда говорит на иностранном языке?", en_example: "Does your friend feel confident enough when he speaks a foreign language?" },
	{
		en: 'promising',
		tr: '[ˈprɒmɪsɪŋ]',
		ru: 'многообещающий',
		ru_example: 'Я хотел бы принять это предложение, потому что это звучит очень многообещающе',
		en_example: "I'd like to take this offer because it sounds very promising",
	},
	{
		en: 'spacious',
		tr: '[ˈspeɪʃəs]',
		ru: 'просторный',
		ru_example: 'Это просторный дом',
		en_example: 'This is a spacious house',
	},
	{
		en: 'powerful',
		tr: '[ˈpaʊəfᵊl]',
		ru: 'мощный',
		ru_example: 'Компьютер не такой мощный',
		en_example: "The computer isn't so powerful",
	},
	{
		en: 'homemade',
		tr: '[ˌhəʊmˈmeɪd]',
		ru: 'домашний, домашнего изготовления',
		ru_example: 'Я действительно обожаю домашнюю еду',
		en_example: 'I really enjoy homemade food',
	},
	{ en: 'wide', tr: '[waɪd]', ru: 'широкий', ru_example: 'Это широкая улица', en_example: "It's a wide street" },

]

export default ADJECTIVES


