const ANIMALS = [
	{ en: 'shrimp', tr: '[ʃrɪmp]', ru: 'креветка' },
	{ en: 'dove', tr: '[dʌv]', ru: 'голубь' },
	{ en: 'lizard', tr: '[ˈlɪzəd]', ru: 'ящерица' },
	{ en: 'beetle', tr: '[ˈbiːtᵊl]', ru: 'жук' },
	{ en: 'mosquito', tr: '[məsˈkiːtəʊ]', ru: 'комар' },
	{ en: 'insect', tr: '[ˈɪnsɛkt]', ru: 'насекомое' },
	{ en: 'swan', tr: '[swɒn]', ru: 'лебедь ' },
	{ en: 'rat', tr: '[ræt]', ru: 'крыса' },
	{ en: 'cockroach', tr: '[ˈkɒkrəʊʧ]', ru: 'таракан' },
	{ en: 'ox / bull', tr: '[ɒks] / [bʊl]', ru: 'бык' },
	{ en: 'mole', tr: '[məʊl]', ru: 'крот' },
	{ en: 'crow', tr: '[krəʊ]', ru: 'ворона' },
	{ en: 'cow', tr: '[kaʊ]', ru: 'корова' },
	{ en: 'snail', tr: '[sneɪl]', ru: 'улитка' },
	{ en: 'rhino', tr: '[ˈraɪnəʊ]', ru: 'носорог' },
	{ en: 'salmon', tr: '[ˈsæmən]', ru: 'лосось' },
	{ en: 'walrus', tr: '[ˈwɔːlrəs]', ru: 'морж' },
	{ en: 'jackal', tr: '[ˈʤækᵊl]', ru: 'шакал' },
	{ en: 'hamster', tr: '[ˈhæmstə]', ru: 'хомяк' },
	{ en: 'ostrich', tr: '[ˈɒstrɪʧ]', ru: 'страус' },
	{ en: 'sparrow', tr: '[ˈspærəʊ]', ru: 'воробей' },
	{ en: 'peacock', tr: '[ˈpiːkɒk]', ru: 'павлин' },
	{ en: 'seagull', tr: '[ˈsiːɡʌl]', ru: 'чайка' },
	{ en: 'ladybug', tr: '[ˈleɪdɪbʌɡ]', ru: 'божья коровка' },
	{ en: 'raccoon', tr: '[rəˈkuːn]', ru: 'енот' },
	{ en: 'hedgehog', tr: '[ˈhɛʤhɒɡ]', ru: 'еж' },
	{ en: 'duckling', tr: '[ˈdʌklɪŋ]', ru: 'утёнок' },
	{ en: 'starfish', tr: '[ˈstɑːfɪʃ]', ru: 'морская звезда' },
	{ en: 'reindeer', tr: '[ˈreɪndɪə]', ru: 'северный олень' },
	{ en: 'jellyfish', tr: '[ˈʤɛlɪfɪʃ]', ru: 'медуза' },
	{ en: 'dragonfly', tr: '[ˈdræɡᵊnflaɪ]', ru: 'стрекоза' },
	{ en: 'guinea pig', tr: '[ˈɡɪni] [pɪɡ]', ru: 'морская свинка' },
	{ en: 'caterpillar', tr: '[ˈkætəpɪlə]', ru: 'гусеница' },
	{ en: 'nightingale', tr: '[ˈnaɪtɪŋɡeɪl]', ru: 'соловей' },
	{ en: 'ram', tr: '[ræm]', ru: 'баран ' },
	{ en: 'yak', tr: '[jæk]', ru: 'як' },
	{ en: 'cod', tr: '[kɒd]', ru: 'треска' },
	{ en: 'tuna', tr: '[ˈʧuːnə]', ru: 'тунец ' },
	{ en: 'cock', tr: '[kɒk]', ru: 'петух' },
	{ en: 'seal', tr: '[siːl]', ru: 'тюлень; печать' },
	{ en: 'calf', tr: '[kɑːf]', ru: 'теленок; голень' },
	{ en: 'wasp', tr: '[wɒsp]', ru: 'оса' },
	{ en: 'pike', tr: '[paɪk]', ru: 'щука' },
	{ en: 'boar', tr: '[bɔː]', ru: 'кабан' },
	{ en: 'lynx', tr: '[lɪŋks]', ru: 'рысь' }
]

export default ANIMALS