const BODY = [
	{ en: 'heel', tr: '[hiːl]', ru: 'пятка' },
	{ en: 'foot', tr: '[fʊt]', ru: 'стопа' },
	{ en: 'feet', tr: '[fiːt]', ru: ' стопы' },
	{ en: 'toe', tr: '[təʊ]', ru: 'палец [на ноге]' },
	{ en: 'leg', tr: '[leɡ]', ru: 'нога [от бедра до щиколотки]' },
	{ en: 'nail', tr: '[neɪl]', ru: 'ноготь' },
	{ en: 'finger', tr: '[ˈfɪŋɡər]', ru: 'палец [на руке]' },
	{ en: 'thumb', tr: '[θʌm]', ru: 'большой палец руки' },
	{ en: 'palm', tr: '[pɑːm]', ru: 'ладонь' },
	{ en: 'wrist', tr: '[rɪst]', ru: 'запястье' },
	{ en: 'elbow', tr: '[ˈelbəʊ]', ru: 'локоть' },
	{ en: 'mustache ', tr: '[ˈmʌstəʃ]', ru: 'усы' },
	{ en: 'forehead', tr: '[ˈfɔːrhed]', ru: 'лоб' },
	{ en: 'eyebrow', tr: '[ˈaɪbraʊ]', ru: 'бровь' },
	{ en: 'ear', tr: '[ɪə]', ru: 'ухо' },
	{ en: 'cheek', tr: '[tʃiːk]', ru: 'щека' },
	{ en: 'chin', tr: '[tʃɪn]', ru: 'подбородок' },
	{ en: 'mouth', tr: '[maʊθ]', ru: 'рот' },
	{ en: 'eyelash', tr: '[ˈaɪlæʃ]', ru: 'ресница' },
	{ en: 'bang [US] / fringe [BR]', tr: '[bæŋ] / [frɪndʒ]', ru: 'чёлка' },
	{ en: 'tooth', tr: '[tuːθ]', ru: 'зуб' },
	{ en: 'teeth', tr: '[tiːθ]', ru: 'зубы' },
	{ en: 'lung', tr: '[lʌŋ]', ru: 'лёгкое' },
	{ en: 'liver', tr: '[ˈlɪvər]', ru: 'печень' },
	{ en: 'spine', tr: '[spaɪn]', ru: 'позвоночник' },
	{ en: 'waist', tr: '[weɪst]', ru: 'талия' },
	{ en: 'hip', tr: '[hip]', ru: 'бедро' },
	{ en: 'neck', tr: '[nek]', ru: 'шея' },
	{ en: 'shoulder', tr: '[ˈʃəʊldər]', ru: 'плечо' },
	{ en: 'chest', tr: '[tʃest]', ru: 'грудь' },
	{ en: 'stomach', tr: '[ˈstʌmək]', ru: 'желудок, живот' }
]

export default BODY